# Generated by Django 5.2.8 on 2026-03-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
